// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxebsmeahtoxaviuttgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZWJzbWVhaHRveGF2aXV0dGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTk4MzEsImV4cCI6MjA1NDc5NTgzMX0.yXjarodeA5CGEXcK4b7Me8nC7qgGYNGXUO2tGnWf1xQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);